node_js: 6
sudo: false
install: npm install
script: true # <-- @todo we can test here
cache:
  apt: true
  directories:
  - node_modules
  - .lanyon
before_cache:
  - rm -f ./node_modules/.bin/which # <-- workaround for https://github.com/travis-ci/travis-ci/issues/5092
before_deploy: node_modules/.bin/lanyon postinstall # <-- unless you already run lanyon postinstall some other way (e.g. via npm scripts/install)
deploy:
  skip_cleanup: true
  provider: script
  script: .lanyon/bin/deploy # <-- this calls 'npm run build:production && npm run deploy'. Travis does not allow commands, only files here..
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
