language: generic
matrix:
  include:
    - os: linux
      sudo: false
    - os: osx

script: npm run build:production

# Travis docs: Note that pull request builds skip deployment step altogether.
# https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on
deploy:
  skip_cleanup: true
  provider: script
  script: _script/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux

# export GHPAGES_URL="https://xxxx@github.com/kvz/locutus.git"
# travis encrypt "GHPAGES_URL=${GHPAGES_URL}"
