language: node_js
cache:
  apt: true
  directories:
    - node_modules
    - deps
node_js:
  - "4"
  - "6"
before_install:
  - rvm install 2.1.1 && rvm --default use 2.1.1 && ruby -v
  - npm install -g yarn@0.16.1
after_install:
  - yarn
