cache:
  apt: true
  yarn: true
  directories:
    - /usr/local/Cellar/

# Since we're npm install-ing ourserves via npm link in a clean /tmp/xxx directory,
# we're skipping the install here
install:
  - true

script:
  # OSX rvm build needs more than 10m no-output-travis-time
  - travis_wait 50 npm run test

before_install:
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then __rvm_unload; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install ruby-build; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew link ruby-build; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install rbenv; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew link rbenv; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then __rvm_unload; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then curl -sSL https://raw.github.com/fesplugas/rbenv-installer/22cc96aa45d06faca5958b1aa1688596198407a3/bin/rbenv-installer | bash; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then export RBENV_ROOT="${HOME}/.rbenv"; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then export PATH="${RBENV_ROOT}/bin:${PATH}"; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then eval "$(rbenv init -)"; fi

os: linux
dist: precise
sudo: false
env: LANYON_ONLY="auto-all" OSDIST="precise"
node_js: "6"
language: node_js

# OSDIST is ignored, but added to easily identify builds in Travis CI's build index, which displays
# env vars in a table, but not os/dists
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      env: LANYON_ONLY="rbenv" OSDIST="precise"
      language: node_js
      node_js: "0.12"
    - os: linux
      dist: trusty
      sudo: required
      env: LANYON_ONLY="system" OSDIST="trusty"
      language: node_js
      node_js: "4"
    - os: linux
      dist: trusty
      sudo: required
      env: LANYON_ONLY="docker" OSDIST="trusty"
      language: node_js
      node_js: "6"
    - os: osx
      osx_image: beta-xcode6.1
      env: LANYON_ONLY="rvm" OSDIST="beta-xcode6.1"
      language: node_js
      node_js: "0.12"
    - os: osx
      osx_image: xcode7.2
      env: LANYON_ONLY="rbenv" OSDIST="xcode7.2"
      language: node_js
      node_js: "4"
    - os: osx
      osx_image: xcode8
      env: LANYON_ONLY="system" OSDIST="xcode8"
      language: node_js
      node_js: "7"
