language: node_js
sudo: false
cache:
  apt: true
  directories:
    - node_modules
    - vendor/gems
    - vendor/bundler
    - /usr/local/Cellar/

node_js:
  - "4"

# Since we're npm install-ing ourserves via npm link in a clean /tmp/xxx directory,
# we're skipping the install here
install:
  - true

before_install:
  - if [[ "${LANYON_ONLY}" == "rbenv" ]]; then brew update; fi
  - if [[ "${LANYON_ONLY}" == "rbenv" ]]; then brew install rbenv; fi

matrix:
  # allow_failures:
  #   - os: osx
  #     osx_image: xcode7.2
  #   - os: osx
  #     osx_image: xcode8
  #   - os: linux
  #     dist: trusty
  include:
    - os: linux
      dist: precise
      sudo: false
      env: LANYON_ONLY="rvm"
      node_js:
        - "0.12"
    - os: linux
      dist: precise
      sudo: false
      env: LANYON_ONLY="rbenv"
      node_js:
        - "6"
    - os: linux
      dist: trusty
      sudo: required
      env: LANYON_ONLY="system"
    - os: linux
      dist: trusty
      sudo: required
      env: LANYON_ONLY="docker"
    - os: osx
      osx_image: beta-xcode6.1
      env: LANYON_ONLY="rvm"
    - os: osx
      osx_image: xcode7.2
      env: LANYON_ONLY="rbenv"
    - os: osx
      osx_image: xcode8
      env: LANYON_ONLY="system"
