cache:
  apt: true
  yarn: true
  directories:
    - /usr/local/Cellar/

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bc

before_install:
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then __rvm_unload; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install ruby-build; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew link ruby-build; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install rbenv; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew link rbenv; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then __rvm_unload; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then curl -sSL https://raw.github.com/fesplugas/rbenv-installer/22cc96aa45d06faca5958b1aa1688596198407a3/bin/rbenv-installer | bash; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then export RBENV_ROOT="${HOME}/.rbenv"; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then export PATH="${RBENV_ROOT}/bin:${PATH}"; fi
  - if [ "${LANYON_ONLY}" = "rbenv" ]  && [ "${TRAVIS_OS_NAME}" == "linux" ]; then eval "$(rbenv init -)"; fi

# We do not want to run `cli.js install` at this point, that's done in the test:acceptance
# via linking. If we run postscripts we get into a chicken-egg situation where install relies on transpiled
# scripts, but that relies on install.
install:
  - type yarn || npm install -g yarn@0.18.1 || true
  - yarn || npm install

script:
  # eslint does not work on old nodes
  - 'if [ "$(bc <<< "${TRAVIS_NODE_VERSION} >= 4")" -eq 1 ]; then npm run lint; fi'
  # babel compile does not work on flat npm structure
  # - 'if [ "$(bc <<< "${TRAVIS_NODE_VERSION} >= 4")" -eq 1 ]; then npm run build; fi'
  - 'if [ "$(bc <<< "${TRAVIS_NODE_VERSION} >= 4")" -eq 1 ]; then npm run build; else nvm install 6 && nvm use 6 && rm -rf node_modules && mkdir node_modules && npm install && npm run build && nvm use ${TRAVIS_NODE_VERSION} && rm -rf node_modules && mkdir node_modules && npm install; fi'
  - 'if [ "$(bc <<< "${TRAVIS_NODE_VERSION} >= 6")" -eq 1 ]; then npm run test; fi'
  # OSX rvm build needs more than 10m no-output-travis-time
  - travis_wait 50 npm run test:acceptance

os: linux
dist: precise
sudo: false
env:
  matrix:
  - SCROLEX_MODE=passthru LANYON_ONLY="auto-all" OSDIST="precise"
  global:
  - secure: Du81N+VYszPmbjdb17tMcKHAKBWlarOYr6Z+kN6h41s8VlS+rmLv9yRlEsxU8+P1x9AA31wwN5duIkyFZr+3GD7mGAjzowHnKZD5j1CF7v0cKoowfJW/mbtodh35/n3j28UQuA/C7OWjeYE5BhVtW7cV3h2Pgdgf1/h9P8jRNeOaMbuhvSsKrQj7lZ5ffzi12wJxWyZDnG1geaSP17cIiqG0B3oGesfY7ASYz+2G/YufgdunFtjMxyfPNfQD+06gxOKo5iFqkjfE84Atgsd+G91vVIxam4gBtVVbAi2qmeB1Dpz9N4sR+XV+u29381KBkflT0JeElABFulr2b5rUCW8ACKWGGzDLOALvFyS12iZjcZrvDag/s9bSm4Gjhf5VdE4ygpAxjSXhSpDJcC1sDeO/oUGoGdia01g9FHM99mFtemciZwxbGRsU7X9+JSEjqh51CmANuB+L/avsd/KVXF7RiKuu9CCTc3XGG6MxXNVUDaFE+wCfQZsMcqLeKzX4aLAMdrTT1VV0ZNQIo/DnvVF4oUvdhhwZlUcY74jBpW3tYnn7i+V66Hj15Ej+S01D/ZCJKP6xP5HgYGy1ArQzGx0tF65fHZ1O51GEZzaIcKFvzqhONDkBGEjulyaEWpb6j9ofJFdbUEkLdbwLdzTfJ8goZyyjmYw74/deg38ttzs=
  - secure: JM5fA4yMjOTPYrsuMSxgEdZH7agmtrYPA0L7xCCgs6btDt5XIyIXtBkn6jW066VtxlU7ruGJHiqM0sW4Fl+rmy/hibFNBfS2ll0Q8TWappD2SOXKW5lgW3FrjhyRXq1vzpnPdHR+01IxrCkPnkTIHsB4y9bGONHLR6bhYrIi7NobobcsCLlRJoedxitHCjATJ0mq+oDpn2tDQesLMtvL7YGEWMHMHbsAgBtAe0O06HBoR8K4pjhrF4cJ/KXucMvVevJSloJHCYvoMSCQXE1xoVbzT0L3hyxVyvqwXnhOWF04Vh4e+pfBybSmRfrUkt08SiMapi1NVGJf1jy/PampRj13ITnAASpeSJQat7Q4Bp7+Ap4PzRmPXAQDwJV+dbhlsk2fTL7PXCDWGTtwCB7pI6+SJOwSvkex4OTFA6y29lYz3GsDdXlbYActK8R8mQ/7R5pbfmEEqhL6UhkUnc/NG7taTdJmiDjaBWyeJU6KVHIbnylq9rtmHs2bMiYJU3keya+7nE6D8PZj8qtG6cxWopNOOIWCwPvfW+tOejHRNwDW9z2+83+Dh+8UHW1qXAiA8zYoA3E1GNQpGWEVUHXOlzbAmhubHujzifB2HdMTuxjuFXziHvJI4HZdh/LPXSzWsBuM/8b7s1/nV8gWISUCgnFZkeH10lGdj6uYC35hP18=
  - secure: XuJgkSTVR/wF2USjCrlVqZiP35R+i8VcslkCS3wK9GfRayuD1r2tpXUqtKMzpLNpLufmZqYTJ/2+B8brMAF8H68lC084kybTXygqC4/mphqJ5ingZAMIfLrTqH4PT4ATLzwg4ecc2C9M1ytjaa0TQv8mKq5mEMT0JeUIz5ddrm5fabZQga/EbuTWr+mTXJ2j+5fy1Y71nXM6tNAwAhYmfbNmOpDN4G+OYc7u7U4vUNXkv8FUOlJeflGFfH64wWE7qtHpO52b+SeWezLf1MYo7VO9+b8xQmRudWzxNM5u5vSjk1g7eCxcXGNxRLHLCtEcyp4AmSRVoO7Tr8XHndY5B69dB3NEql3mlEkAqpgW3OY2fIK2KwOydpv/IOsewafG8qVgAtw7iANxkKPkjg52EedfTJ943hILfzkXpRmCvX5qxSUbHrsNad9u7V7QaKF+kX4No1qAE3GpGXsPKpGQv2UOiFMbBYeZEzQYmHj0vKM9+QE8n7BA95kkm4XqrfDSmRB2V+hBK13F/EWpV21+xNBYbBK8+iGCk4hI/AQo8y5Xo4dEKb4rllMC+P4hv9qBNVVXzsetlWgf89H7ubFIxbl9rzD5q9eMBI6/Vhoy9/wjHUrUkvpZAyol/1M7w3WA6PXuL90US6ObFffa6RxpMCGNL3VH4541vJL60eJ1O/A=
node_js: '6'
language: node_js

# OSDIST is ignored, but added to easily identify builds in Travis CI's build index, which displays
# env vars in a table, but not os/dists
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      env: SCROLEX_MODE=passthru LANYON_ONLY="rbenv" OSDIST="precise"
      language: node_js
      node_js: "0.12"
    - os: linux
      dist: trusty
      sudo: required
      env: SCROLEX_MODE=passthru LANYON_ONLY="system" OSDIST="trusty"
      language: node_js
      node_js: "4"
    - os: linux
      dist: trusty
      sudo: required
      env: SCROLEX_MODE=passthru LANYON_ONLY="docker" OSDIST="trusty"
      language: node_js
      node_js: "6"
    - os: osx
      osx_image: beta-xcode6.1
      env: SCROLEX_MODE=passthru LANYON_ONLY="rvm" OSDIST="beta-xcode6.1"
      language: node_js
      node_js: "0.12"
    - os: osx
      osx_image: xcode7.2
      env: SCROLEX_MODE=passthru LANYON_ONLY="rbenv" OSDIST="xcode7.2"
      language: node_js
      node_js: "4"
    - os: osx
      osx_image: xcode8
      env: SCROLEX_MODE=passthru LANYON_ONLY="system" OSDIST="xcode8"
      language: node_js
      node_js: "7"
before_cache:
- rm -f ./node_modules/.bin/which
before_deploy:
- cd website && npm link lanyon && cd ..
- env LANYON_PROJECT=./website node ./lib/cli.js install
deploy:
  skip_cleanup: true
  provider: script
  script: website/.lanyon/bin/deploy
  on:
    branch: master
    node: 6
    condition: $LANYON_ONLY = docker
