language: node_js
sudo: false
cache:
  apt: true
  directories:
    - node_modules
    - vendor/gems
    - vendor/bundler
    - /usr/local/Cellar/
node_js:
  - "0.12"
  - "4"
  - "6"

# Since we're npm install-ing ourserves via npm link in a clean /tmp/xxx directory,
# we're skipping the install here
install:
  - true

before_install:
  - if [[ "${PRE_INSTALL_RBENV}" == "1" ]]; then brew update; fi
  - if [[ "${PRE_INSTALL_RBENV}" == "1" ]]; then brew install rbenv; fi

matrix:
  matrix:
    allow_failures:
      - os: osx
        osx_image: xcode7.2
      - os: osx
        osx_image: xcode8
      - os: linux
        dist: trusty
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: LANYON_DISABLE="system"
    - os: osx
      osx_image: beta-xcode6.1
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8
      env: PRE_INSTALL_RBENV=1 LANYON_DISABLE="rvm docker"
